### ISSUE TITLE
rocm layout change

### ISSUE THREAD

**Issue by moultonsa** [jungwonkim/amd-toy#1]
Hi Jungwon,

ROCM has changed the layout, merging HIP in organically.  To get the toy to work I did the following.

FYI

  -s

hsm@cousteau:~/git/github/amd-toy[main !?]$ git diff Makefile
diff --git a/Makefile b/Makefile
index 8e3127a..5abbcf9 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 all:toy kernel.code

 toy: toy.cpp
-       g++ -I /opt/rocm/hip/include/ -o $@ $? -L /opt/rocm/hip/lib/ -lamdhip64
+       g++ -I /opt/rocm/include -o $@ $? -L /opt/rocm/lib/ -lamdhip64

**Comment by jungwonkim** [comment]
Fixed. Thank you, Steve!
